### ISSUE TITLE
Setting language option causes a javascript error

### ISSUE THREAD

**Issue by asahnoln** [asofter/yii2-imperavi-redactor#26]
Good afternoon.

I tried setting a language in the options array to Russian, but this action causes a javascript error which prevents Redactor from loading.
```
redactor.js:4887 Uncaught TypeError: Cannot read property 'html' of undefined
```
Sample PHP code:
```php
echo $form->field($model, 'content')->widget(\yii\imperavi\Widget::className(), [
        'options' => [
            'lang' => 'ru',
        ],
]);
```
The problem happens with just the widget without activeField as well:
```php
echo \yii\imperavi\Widget::widget([
        'options' => [
            'lang' => 'it',
        ],
]);
```
It seems the error occurs with any language except English.

**Comment by gonimar** [comment]
:+1:
