### ISSUE TITLE
How to set redactor callback in widget options

### ISSUE THREAD

**Issue by cicsolutions** [asofter/yii2-imperavi-redactor#43]
Hello, I can't seem to understand how we can use the widget and be able to set redactor callback functions.  The redactor callback functions are javascript functions, but we are configuring the redactor options in the php widget.  Therefore, the javascript function becomes a string when it is json encoded and is not executable as a javascript function.

It seems like there must be a way to address this challenge.  Any guidance you can offer is greatly appreciated!  Many thanks for all you do!

**Comment by asofter** [comment]
Hello.

```php
'options' => [
    'keydownCallback' => new \yii\web\JsExpression("function(e) { yourFunctionOrSomeCodeHere(); }")
]
```

**Comment by cicsolutions** [comment]
Thank you so, so much!  I've been trying to figure this out for several days now.  I appreciate your input and assistance tremendously!
