### ISSUE TITLE
Label and validation errors are not showing

### ISSUE THREAD

**Issue by alexweb** [asofter/yii2-imperavi-redactor#45]
Label and validation errors are not showing
```php
echo yii\imperavi\Widget::widget([
                'model' => $model,
                'attribute' => 'content',
            ]);
```

**Comment by asofter** [comment]
```php
 <?= $form->field($messageModel, 'content')->widget(\yii\imperavi\Widget::className(), [
                   'model' => $messageModel,
                   'attribute' => 'content'
                ]); ?>
```

**Comment by alexweb** [comment]
In this case validaion errors are not showing.

**Comment by asofter** [comment]
Only after submitting after $model->validate();

It works for me. And don't forget that Imperavi doesn't have blank text. It is
```
<p></p>
```

**Comment by alexweb** [comment]
I mean ajax and client validation errors is not showing

**Comment by asofter** [comment]
Yes, of course. You have to set up it for imperavi with settings of the imperavi plugin. 

Try 'enableAjaxValidation' => true, but create custom validation function for imperavi empty(strip_tags($text))

**Comment by alexweb** [comment]
Ajax validation is enabled and returns an error for that filed, But the imperavi doesn't show it.
